### ISSUE TITLE
Add GraphQL to Your Jetpack Compose Apps

### ISSUE THREAD

**Issue by talalgit** [apollographql/apollo-kotlin-tutorial#25]
The repo for Add GraphQL to Your Jetpack Compose Apps doesn't exist, please check

https://github.com/apollographql/apollo-kotlin-tutorial/tree/compose

**Comment by BoD** [comment]
Hi! We plan to bring back an up to date version of this to the tutorial. In the meantime you should still be able to be inspired by [the blog post](https://www.apollographql.com/blog/frontend/add-graphql-to-your-jetpack-compose-apps/), even if the code snippets are a bit outdated.

**Comment by jpvajda** [comment]
@talalgit 👋  We are currently working in an update to the[ original blog post about Jetpack compose](https://www.apollographql.com/blog/frontend/add-graphql-to-your-jetpack-compose-apps/) as it's outdated and like you mentioned the branch was previously deleted.  I've linked the PR we are working from in this issue. Thanks for you patience!

**Comment by jpvajda** [comment]
@talalgit 👋  We've done some work to update [this blog](https://www.apollographql.com/blog/frontend/add-graphql-to-your-jetpack-compose-apps/) and also added a new [compose branch](https://github.com/apollographql/apollo-kotlin-tutorial/tree/compose) to the tutorial repo for reference. Just let us know if you have any other issues.
